let muckscan take the repo url as a parameter
navikt/muckscan pull request #3
Opened 2018-06-05 17:52 UTC by jan-berge-ommedal

2018-06-06 07:39 UTC, kimtore requested changes
Nice change, this will enable Windows users to easily scan a remote repository.
I'm concerned about the usability of the image when the entrypoint is changed without supporting dropping into a shell. If you have to change `CMD` into `ENTRYPOINT`, please provide a way to run a shell instead of the default command without having to override the Docker entrypoint on the command line.

2018-06-09 11:34 UTC, jan-berge-ommedal commented
@ambientsound like this? https://github.com/navikt/muckscan/pull/3/commits/eb3471b85b1e4fdb0c81b36a91ebba74b2326ecc

2018-06-11 07:35 UTC, kimtore commented
Yes, and with the latest change supports running any supported command directly through the entry point.

2018-06-11 07:35 UTC, kimtore approved these changes

2018-06-11 07:36 UTC, merged